### ISSUE TITLE
可以本地使用iscroll吗

### ISSUE THREAD

**Issue by mixingyu** [baijunjie/jQuery-photoClip#96]
我安装这个非常慢, 还会失败"iscroll": "baijunjie/iscroll",

**Comment by mixingyu** [comment]
Error: [vha-photoclip@3.4.7 › iscroll@github:baijunjie/iscroll] Run "C:\WINDOWS\system32\cmd.exe /d /s /c git clone https://github.com/baijunjie/iscroll.git F:\Project\Yummy\yummy-app\vue\node_modules\.tmp\7d1cfbef-6fad-49b8-bc2d-7893991bc26f" error, exit code 128
    at module.exports (F:\software\nodejs\node_modules\cnpm\node_modules\npminstall\lib\download\git.js:51:11)
    at module.exports.throw (<anonymous>)
    at onRejected (F:\software\nodejs\node_modules\cnpm\node_modules\co\index.js:81:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by mixingyu** [comment]
[iscroll@baijunjie/iscroll] install iscroll from git github:baijunjie/iscroll, may be very slow, please keep patience

**Comment by mixingyu** [comment]
Error: [iscroll@baijunjie/iscroll] Run "C:\WINDOWS\system32\cmd.exe /d /s /c git clone https://github.com/baijunjie/iscroll.git F:\Project\github\cordova-plugin-vha\vha-photoclip\node_modules\.tmp\d1b8b8d7-360c-4ec3-b34e-20e436412a00" error, exit code 128
    at module.exports (F:\software\nodejs\node_modules\cnpm\node_modules\npminstall\lib\download\git.js:51:11)
    at module.exports.throw (<anonymous>)
    at onRejected (F:\software\nodejs\node_modules\cnpm\node_modules\co\index.js:81:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by mixingyu** [comment]
依赖的插件能本地化一下嘛  - - 装起来真的有很多问题呀。

**Comment by baijunjie** [comment]
这或许跟国内的防火墙有关，如果不能安装的话，建议修改一下代码的引入方式，使用本地的 iscroll

**Comment by mixingyu** [comment]
> 这或许跟国内的防火墙有关，如果不能安装的话，建议修改一下代码的引入方式，使用本地的iscroll

我搞定了，谢谢。不只是安装，我调用transpileDependencies转es5也遇到了很大的麻烦。最后在public引入的编译好的
